song_data = read.csv("/Users/anato/Desktop/Università/Data Science 4 Citiziens/song_data1.csv/song_data.csv")
na = is.na(song_data)
library(dplyr)
df = song_data %>% distinct()
df2 <- df %>% distinct(song_name, .keep_all = TRUE)
